num_classes: 18

semantic_names:
  0: 'others'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
  17: 'empty'